name: cyworld_refac_backend

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install project dependencies, test and build
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    needs: buildAndTest
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}
      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install project dependencies and build
      - name: Install dependencies
        run: npm install
      # TS 파일들을 빌드해서 build 폴더에 js 파일들을 만들기 때문에
      # 아래에서 zip 파일 구성 시 src 폴더를 제외한 것을 확인할 수 있다.
      - name: Run build
        run: npm run build

      - name: zip file
        run: zip -r cicdtest.zip ./build ./scripts ./appspec.yml ./.env ./package.json

      - name: AWS connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./cicdtest.zip s3://cyworld-refac/build/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name cyworld-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name GROUP
          --s3-location bucket=cyworld-refac,bundleType=zip,key=build/cicdtest.zip
