name: project-cicd

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.15.0]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.15.0]
    needs: buildAndTest
    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build

      - name: zip file
        run: zip -r cicdtest.zip ./build/src ./build/server.js ./scripts ./appspec.yml ./.env ./package.json

      - name: AWS connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./cicdtest.zip s3://cyworld-refac/build/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name codedeploy-app
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name codedeploy-group
          --s3-location bucket=cyworld-refac,bundleType=zip,key=build/cicdtest.zip